testing

diff --git a/.github/workflows/web-integration-tests.yml b/.github/workflows/web-integration-tests.yml
--- a/.github/workflows/web-integration-tests.yml
+++ b/.github/workflows/web-integration-tests.yml
@@ -58,8 +58,13 @@ jobs:
         run: |
           for test in integration_test/*.dart; do
             echo "Running test: $test"
-            timeout 2m xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" flutter drive --driver=test_driver/integration_test.dart --target=$test -d chrome --web-port=4200 --dart-define=MAILOSAUR_API_KEY=${{ secrets.MAILOSAUR_API_KEY }} || exit 1
-            echo "Test completed: $test"
+            timeout 1m xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" flutter drive --driver=test_driver/integration_test.dart --target=$test -d chrome --web-port=4200 --dart-define=MAILOSAUR_API_KEY=${{ secrets.MAILOSAUR_API_KEY }}
+            if [ $? -eq 0 ]; then
+              echo "Test completed successfully: $test"
+            else
+              echo "Test failed: $test"
+              exit 1
+            fi
           done
         working-directory: ./integrationtestapp
         env:
