testing

diff --git a/.github/workflows/web-integration-tests.yml b/.github/workflows/web-integration-tests.yml
--- a/.github/workflows/web-integration-tests.yml
+++ b/.github/workflows/web-integration-tests.yml
@@ -58,7 +58,14 @@ jobs:
         run: |
           for test in integration_test/*.dart; do
             echo "Running test: $test"
-            xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" flutter drive --driver=test_driver/integration_test.dart --target=$test -d chrome --web-port=4200 --dart-define=MAILOSAUR_API_KEY=${{ secrets.MAILOSAUR_API_KEY }} || exit 1
+            xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" flutter drive --driver=test_driver/integration_test.dart --target=$test -d chrome --web-port=4200 --dart-define=MAILOSAUR_API_KEY=${{ secrets.MAILOSAUR_API_KEY }}
+            RESULT=$?
+            echo "Test result: $RESULT"
+            if [ $RESULT -ne 0 ]; then
+              echo "Test failed: $test"
+              exit 1
+            fi
+            echo "Test completed: $test"
           done
         working-directory: ./integrationtestapp
         env:
